load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "SourceRootGuesserTest",
    size = "small",
    src = "SourceRootGuesserTest.kt",
    deps = [
        "//commons",
        "//server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync/languages",
    ],
)
