load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "FormatTest",
    size = "small",
    src = "FormatTest.kt",
    deps = [
        "//commons/src/main/java/org/jetbrains/bsp/bazel/commons",
    ],
)
