package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'E2eTestsE2eBazelBspJava11ProjectTestTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("E2eTestsE2eBazelBspJava11ProjectTestTest")) {
    dependencies {
        expect(RelativeId("UnitTestsUnitTests")) {
            snapshot {
                onDependencyFailure = FailureAction.CANCEL
                onDependencyCancel = FailureAction.CANCEL
            }
        }
        update(RelativeId("UnitTestsUnitTests")) {
            snapshot {
                onDependencyFailure = FailureAction.IGNORE
                onDependencyCancel = FailureAction.CANCEL
            }
        }

    }
}
