package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.BazelStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.bazel
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'E2eTestsE2eBazelBspLocalJdkTestTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("E2eTestsE2eBazelBspLocalJdkTestTest")) {
    expectSteps {
        script {
            name = "Install necessary pakcages via dockerized Ubuntu"
            scriptContent = """
                #!/bin/bash
                set -euxo pipefail
                
                apt-get update -q
                apt-get install -y build-essential
                
                # check installation
                gcc --version ||:
                find / -name 'cc1plus' 2>/dev/null ||:
                
                #install bazelisk
                curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.15.0/bazelisk-linux-amd64 -o  \
                "/usr/bin/bazel"
                
                chmod +x "/usr/bin/bazel"
                
                #check bazel working
                bazel version ||:
            """.trimIndent()
            dockerImage = "ubuntu:focal"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
            dockerRunParameters = """
                -v /usr/:/usr/
                -v /etc/:/etc/
            """.trimIndent()
        }
        script {
            name = "set JDK to 11"
            scriptContent = """
                #!/bin/bash
                set -euxo pipefail
                
                export PATH="%env.JDK_11_0%/bin:(${'$'})PATH"
                echo "##teamcity[setParameter name='env.PATH' value='(${'$'})PATH']"
                
                which java
            """.trimIndent()
        }
        bazel {
            name = "test //e2e:BazelBspLocalJdkTest"
            command = "run"
            targets = "//e2e:BazelBspLocalJdkTest"
            logging = BazelStep.Verbosity.Diagnostic
            param("toolPath", "/usr/bin")
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                #!/bin/bash
                set -euxo pipefail
                
                export PATH="%env.JDK_11_0%/bin:${'$'}PATH"
                echo "##teamcity[setParameter name='env.PATH' value='${'$'}PATH']"
                
                which java
            """.trimIndent()
        }
    }
}
