package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PipelineResults'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PipelineResults")) {
    features {
        remove {
            pullRequests {
                provider = jetbrainsSpace {
                    filterTargetBranch = "+:<default>"
                    authType = connection {
                        connectionId = "PROJECT_EXT_2845"
                    }
                }
            }
        }
    }
}
