package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseNewRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseNewRelease")) {
    expectSteps {
        script {
            scriptContent = """
                set -ex
                apt-get update
                apt-get install -y python3-pip
                pip3 install lxml
                cd "/usr/local/lib/bazel/bin" && curl -fLO https://releases.bazel.build/5.1.0/release/bazel-5.1.0-linux-x86_64 && chmod +x bazel-5.1.0-linux-x86_64 && cd -
                echo %env.GPG_SECRET% | base64 -di | gpg --import
                bazel run --stamp \
                  --define "maven_user=%jetbrains.sonatype.access.token.username%" \
                  --define "maven_password=%jetbrains.sonatype.access.token.password%" \
                  //server/src/main/java/org/jetbrains/bsp/bazel:bsp.publish
            """.trimIndent()
            dockerImage = "gcr.io/cloud-marketplace-containers/google/bazel"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = """
                set -ex
                apt-get update
                apt-get install -y python3-pip
                pip3 install lxml
                cd "/usr/local/lib/bazel/bin" && curl -fLO https://releases.bazel.build/6.0.0/release/bazel-6.0.0-linux-x86_64 && chmod +x bazel-6.0.0-linux-x86_64 && cd -
                echo %env.GPG_SECRET% | base64 -di | gpg --import
                bazel run --stamp \
                  --define "maven_user=%jetbrains.sonatype.access.token.username%" \
                  --define "maven_password=%jetbrains.sonatype.access.token.password%" \
                  //server/src/main/java/org/jetbrains/bsp/bazel:bsp.publish
            """.trimIndent()
        }
    }
}
