load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "WorkspaceContextConstructorTest",
    size = "small",
    srcs = ["WorkspaceContextConstructorTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "BazelPathSpecMapperTest",
    size = "small",
    srcs = ["BazelPathSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "BuildFlagsSpecMapperTest",
    size = "small",
    srcs = ["BuildFlagsSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "BuildManualTargetsSpecMapperTest",
    size = "small",
    srcs = ["BuildManualTargetsSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "TargetsSpecMapperTest",
    size = "small",
    srcs = ["TargetsSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "DotBazelBspDirPathSpecMapperTest",
    size = "small",
    srcs = ["DotBazelBspDirPathSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "ImportDepthSpecMapperTest",
    size = "small",
    srcs = ["ImportDepthSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)

kt_junit5_test(
    name = "ProduceTraceLogSpecMapperTest",
    size = "small",
    srcs = ["ProduceTraceLogSpecMapperTest.kt"],
    associates = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext",
)
