load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "DopeFilesTest",
    size = "small",
    src = "DopeFilesTest.kt",
    deps = [
        "//utils/src/main/kotlin/org/jetbrains/bsp/bazel/utils/dope",
    ],
)

kt_test(
    name = "DopeTempTest",
    size = "small",
    src = "DopeTempTest.kt",
    deps = [
        "//utils/src/main/kotlin/org/jetbrains/bsp/bazel/utils/dope",
    ],
)
