load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "InternalAspectsResolverTest",
    size = "small",
    src = "InternalAspectsResolverTest.kt",
    deps = [
        "//server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bsp/info",
        "//server/src/main/kotlin/org/jetbrains/bsp/bazel/server/bsp/utils",
    ],
)
