load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "WorkspaceContextTargetsEntityMapperTest",
    size = "small",
    srcs = ["WorkspaceContextTargetsEntityMapperTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.workspacecontext.entries.mappers",
    deps = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext/entries/mappers",
    ],
)
