package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    expectBuildTypesOrder()
    buildTypesOrderIds = arrayListOf(RelativeId("FormatBuildifier"), RelativeId("FormatGoogleJavaFormat"), RelativeId("BuildBuildTheProject"), RelativeId("UnitTestsUnitTests"), RelativeId("E2eTestsE2eBazelBspCppProjectTestTest"), RelativeId("E2eTestsE2eBazelBspLocalJdkTestTest"), RelativeId("E2eTestsE2eBazelBspRemoteJdkTestTest"), RelativeId("E2eTestsE2eBazelBspSampleRepoTestTest"), RelativeId("ReleaseNewRelease"), RelativeId("PipelineResults"))
}
