package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'GitHub'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("GitHub")) {
    expectBuildTypesOrder(RelativeId("GitHubFormatBuildifier"), RelativeId("GitHubBuildBuildBazelBsp"), RelativeId("GitHubUnitTestsUnitTests"), RelativeId("GitHubE2eTestsE2eSampleRepoTest"), RelativeId("GitHubE2eTestsE2eLocalJdkTest"), RelativeId("GitHubE2eTestsE2eRemoteJdkTest"), RelativeId("GitHubE2eTestsE2eServerDownloadsBazeliskTest"), RelativeId("GitHubE2eTestsE2eKotlinProjectTest"), RelativeId("GitHubE2eTestsE2eAndroidProjectTest"), RelativeId("GitHubE2eTestsE2eAndroidKotlinProjectTest"), RelativeId("GitHubE2eTestsE2eEnabledRulesTest"), RelativeId("GitHubE2eTestsPluginRun"), RelativeId("GitHubBenchmark1001Targets"), RelativeId("GitHubResults"))
    buildTypesOrderIds = arrayListOf(RelativeId("GitHubFormatBuildifier"), RelativeId("GitHubBuildBuildBazelBsp"), RelativeId("GitHubUnitTestsUnitTests"), RelativeId("GitHubE2eTestsE2eSampleRepoTest"), RelativeId("GitHubE2eTestsE2eLocalJdkTest"), RelativeId("GitHubE2eTestsE2eRemoteJdkTest"), RelativeId("GitHubE2eTestsE2eServerDownloadsBazeliskTest"), RelativeId("GitHubE2eTestsE2eKotlinProjectTest"), RelativeId("GitHubE2eTestsE2eAndroidProjectTest"), RelativeId("GitHubE2eTestsE2eAndroidKotlinProjectTest"), RelativeId("GitHubE2eTestsE2eEnabledRulesTest"), RelativeId("GitHubE2eTestsPluginRun"))
}
