load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "LabelTest",
    size = "small",
    srcs = ["LabelTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.sync.model",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/sync",
    ],
)
