package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'BazelBspVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("BazelBspVcs")) {
    val expected = GitVcsRoot({
        id("BazelBspVcs")
        name = "bazel-bsp"
        url = "https://github.com/JetBrains/bazel-bsp.git"
        branch = "master"
        branchSpec = "refs/heads/(*)"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = """
            -:team-city
            +|refs/heads/(*)
        """.trimIndent()
    }

}
