package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'SpaceVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("SpaceVcs")) {
    val expected = GitVcsRoot({
        id("SpaceVcs")
        name = "bazel-bsp-space"
        url = "https://git.jetbrains.team/bazel/bazel-bsp.git"
        branch = "master"
        branchSpec = "+:refs/heads/*"
        authMethod = token {
            userName = "x-oauth-basic"
            tokenId = "tc_token_id:CID_ee3bac3e4aa54bdf48fee3b7b53cbc31:-1:2a418eac-8e77-4bf7-8046-fe78debdedba"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "x-oauth-basic"
            tokenId = "tc_token_id:CID_ee3bac3e4aa54bdf48fee3b7b53cbc31:-1:a33c5da5-4562-48ee-b741-892de333fbe9"
        }
    }

}
