package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'SpaceVcs'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("SpaceVcs")) {
    val expected = GitVcsRoot({
        id("SpaceVcs")
        name = "bazel-bsp-space"
        url = "https://git.jetbrains.team/bazel/bazel-bsp.git"
        branch = "master"
        branchSpec = "+:refs/heads/*"
        authMethod = password {
            userName = "x-oauth-basic"
            password = "credentialsJSON:4efcb75d-2f9b-47fd-a63b-fc2969a334f5"
        }
        param("oauthProviderId", "PROJECT_EXT_15")
        param("tokenType", "permanent")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        param("oauthProviderId", "")
        param("tokenType", "")
    }

}
