load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "ProjectViewExcludableListSectionGeneratorTest",
    size = "small",
    srcs = ["ProjectViewExcludableListSectionGeneratorTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.projectview.generator",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)

kt_junit5_test(
    name = "ProjectViewListSectionGeneratorTest",
    size = "small",
    srcs = ["ProjectViewListSectionGeneratorTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.projectview.generator",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)

kt_junit5_test(
    name = "ProjectViewSingletonSectionGeneratorTest",
    size = "small",
    srcs = ["ProjectViewSingletonSectionGeneratorTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.projectview.generator",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)
