load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "commons",
    visibility = ["//visibility:public"],
    exports = [
        "//commons/src/main/java/org/jetbrains/bsp/bazel/commons",
    ],
)
