load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "commons",
    visibility = ["//visibility:public"],
    exports = [
        "//commons/src/main/java/org/jetbrains/bsp/bazel/commons",
    ],
)
