load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "loggers",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:ch_epfl_scala_bsp4j",
    ],
)
