load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "workspacecontext",
    visibility = ["//visibility:public"],
    exports = [
        "//executioncontext/workspacecontext/src/main/java/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)
