load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "InstallationContextJavaPathEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextJavaPathEntityMapperTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.installationcontext.entities.mappers",
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
    ],
)

kt_junit5_test(
    name = "InstallationContextDebuggerAddressEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextDebuggerAddressEntityMapperTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.installationcontext.entities.mappers",
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
    ],
)
