load("//:junit5.bzl", "java_junit5_test")

java_junit5_test(
    name = "InstallationContextJavaPathEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextJavaPathEntityMapperTest.java"],
    test_package = "org.jetbrains.bsp.bazel.installationcontext.entities.mappers",
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
    ],
)

java_junit5_test(
    name = "InstallationContextDebuggerAddressEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextDebuggerAddressEntityMapperTest.java"],
    test_package = "org.jetbrains.bsp.bazel.installationcontext.entities.mappers",
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
    ],
)
