load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "InstallationContextJavaPathEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextJavaPathEntityMapperTest.java"],
    runtime_deps = [
        "@maven//:junit_junit",
    ],
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
        "@maven//:org_assertj_assertj_core",
    ],
)

java_test(
    name = "InstallationContextDebuggerAddressEntityMapperTest",
    size = "small",
    srcs = ["InstallationContextDebuggerAddressEntityMapperTest.java"],
    runtime_deps = [
        "@maven//:junit_junit",
    ],
    deps = [
        "//executioncontext/installationcontext/src/main/java/org/jetbrains/bsp/bazel/installationcontext/entities/mappers",
        "@maven//:org_assertj_assertj_core",
    ],
)
