load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "logger",
    visibility = ["//visibility:public"],
    exports = [
        "//logger/src/main/java/org/jetbrains/bsp/bazel/logger",
    ],
)
