load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "logger",
    visibility = ["//visibility:public"],
    exports = [
        "//logger/src/main/kotlin/org/jetbrains/bsp/bazel/logger",
    ],
)
