java_library(
    name = "common",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@io_bazel//src/main/protobuf:analysis_java_proto",
        "@maven//:com_google_guava_guava",
    ],
)
