load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "reglob",
    srcs = ["Reglob.kt"],
    visibility = ["//server:__subpackages__"],
    deps = ["@maven//:com_google_code_gson_gson"],
)
