load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "installationcontext",
    visibility = ["//visibility:public"],
    exports = [
        "//executioncontext/installationcontext/src/main/kotlin/org/jetbrains/bsp/bazel/installationcontext",
    ],
)
