load("//:junit5.bzl", "java_junit5_test")

java_junit5_test(
    name = "ProjectViewRawSectionsTest",
    size = "small",
    srcs = ["ProjectViewRawSectionsTest.java"],
    test_package = "org.jetbrains.bsp.bazel.projectview.parser.splitter",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/splitter",
    ],
)

java_junit5_test(
    name = "ProjectViewRawSectionTest",
    size = "small",
    srcs = ["ProjectViewRawSectionTest.java"],
    test_package = "org.jetbrains.bsp.bazel.projectview.parser.splitter",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/splitter",
    ],
)

java_junit5_test(
    name = "ProjectViewSectionSplitterTest",
    size = "small",
    srcs = ["ProjectViewSectionSplitterTest.java"],
    test_package = "org.jetbrains.bsp.bazel.projectview.parser.splitter",
    deps = [
        "//executioncontext/projectview/src/main/java/org/jetbrains/bsp/bazel/projectview/parser/splitter",
    ],
)
