load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "dope",
    visibility = ["//visibility:public"],
    exports = [
        "//utils/src/main/kotlin/org/jetbrains/bsp/bazel/utils/dope",
    ],
)
