load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "LabelTest",
    size = "small",
    src = "LabelTest.kt",
    deps = [
        "//server/src/main/kotlin/org/jetbrains/bsp/bazel/server/sync",
    ],
)
