load("//:junit5.bzl", "java_junit5_test")

java_junit5_test(
    name = "CliOptionsProviderTest",
    size = "small",
    srcs = ["CliOptionsProviderTest.java"],
    test_package = "org.jetbrains.bsp.bazel.install.cli",
    deps = [
        "//install/src/main/java/org/jetbrains/bsp/bazel/install/cli",
    ],
)
