load("//:junit5.bzl", "java_junit5_test")

java_junit5_test(
    name = "SemanticVersionTest",
    size = "small",
    srcs = ["SemanticVersionTest.java"],
    test_package = "org.jetbrains.bsp.bazel.bazelrunner",
    deps = [
        "//bazelrunner",
    ],
)
