load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "ProjectViewSectionDummyVerboseValidatorTest",
    size = "small",
    srcs = ["ProjectViewSectionDummyVerboseValidatorTest.java"],
    runtime_deps = [
        "@maven//:junit_junit",
    ],
    deps = [
        "//executioncontext/api/src/main/java/org/jetbrains/bsp/bazel/executioncontext/api/entries/validators/predefined",
    ],
)
