load("//:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "BloopExporterTests",
    size = "small",
    srcs = ["BloopExporterTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.bloop",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_junit5_test(
    name = "BspModuleExporterTest",
    size = "small",
    srcs = ["BspModuleExporterTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.bloop",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_junit5_test(
    name = "ClasspathRewriterTest",
    size = "small",
    srcs = ["ClasspathRewriterTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.bloop",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_junit5_test(
    name = "ReGlobberTest",
    size = "small",
    srcs = ["ReGlobberTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.bloop",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_junit5_test(
    name = "SourceSetRewriterTest",
    size = "small",
    srcs = ["SourceSetRewriterTest.kt"],
    test_package = "org.jetbrains.bsp.bazel.server.bloop",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)
