load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "BloopExporterTest",
    size = "small",
    src = "BloopExporterTest.kt",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_test(
    name = "BspModuleExporterTest",
    size = "small",
    src = "BspModuleExporterTest.kt",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_test(
    name = "ClasspathRewriterTest",
    size = "small",
    src = "ClasspathRewriterTest.kt",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_test(
    name = "ReGlobberTest",
    size = "small",
    src = "ReGlobberTest.kt",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)

kt_test(
    name = "SourceSetRewriterTest",
    size = "small",
    src = "SourceSetRewriterTest.kt",
    deps = [
        "//server/src/main/java/org/jetbrains/bsp/bazel/server/bloop",
    ],
)
