load("@//rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "EnvironmentCreatorTest",
    size = "small",
    src = "EnvironmentCreatorTest.kt",
    deps = [
        "//install/src/main/java/org/jetbrains/bsp/bazel/install",
    ],
)
