load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary")

scala_binary(
    name = "binary",
    srcs = ["Example.scala"],
    args = [
        "arg1",
        "arg2",
    ],
    main_class = "example.Example",
)
