name: Update dependencies


on:
  workflow_dispatch:
  schedule:
   - cron: '0 4 * * 6'

jobs:
  bazel-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: VirtusLab/bazel-steward@v0.0.9
