name: Format

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: agluszak/bazel-buildifier-action@v0.3
      - run: git diff --exit-code
