name: Format

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  google-java-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
      - run: git diff --exit-code
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -f -L -o /usr/bin/buildifier \
          "https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier" \
          && chmod +x /usr/bin/buildifier
      - run: buildifier -r .
      - run: buildifier --lint=fix -r .
      - run: git diff --exit-code
