workspace(name = "cpp_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

GTEST_SHA = "5ab508a01f9eb089207ee87fd547d290da39d015"

http_archive(
    name = "com_google_googletest",
    sha256 = "755f9a39bc7205f5a0c428e920ddad092c33c8a1b46997def3f1d4a82aded6e1",
    strip_prefix = "googletest-{}".format(GTEST_SHA),
    urls = ["https://github.com/google/googletest/archive/{}.zip".format(GTEST_SHA)],
)

local_repository(
    name = "intellij_aspect",
    path = "/home/andre/Projects/bazel-intellij/aspect",
)
