workspace(name = "cpp_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# ======================================================================================================================
# ----------------------------------------------------------------------------------------------------------------------
# ======================================================================================================================
# com_google_googletest

COM_GOOGLE_GOOGLETEST_TAG = "release-1.11.0"

COM_GOOGLE_GOOGLETEST_SHA = "353571c2440176ded91c2de6d6cd88ddd41401d14692ec1f99e35d013feda55a"

http_archive(
    name = "com_google_googletest",
    sha256 = COM_GOOGLE_GOOGLETEST_SHA,
    strip_prefix = "googletest-{}".format(COM_GOOGLE_GOOGLETEST_TAG),
    url = "https://github.com/google/googletest/archive/{}.zip".format(COM_GOOGLE_GOOGLETEST_TAG),
)
